version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd app
      - npm install
  build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - app/**/*
